INSERT INTO inventory.products_on_hand (product_id, quantity) VALUES (101, 3);
INSERT INTO inventory.products_on_hand (product_id, quantity) VALUES (102, 8);
INSERT INTO inventory.products_on_hand (product_id, quantity) VALUES (103, 18);
INSERT INTO inventory.products_on_hand (product_id, quantity) VALUES (104, 4);
INSERT INTO inventory.products_on_hand (product_id, quantity) VALUES (105, 5);
INSERT INTO inventory.products_on_hand (product_id, quantity) VALUES (106, 0);
INSERT INTO inventory.products_on_hand (product_id, quantity) VALUES (107, 44);
INSERT INTO inventory.products_on_hand (product_id, quantity) VALUES (108, 2);
INSERT INTO inventory.products_on_hand (product_id, quantity) VALUES (109, 5);